install.packages("rmarkdown")
install.packages("urltools")
install.packages("jsonlite")
install.packages("reticulate")
install.packages("DT")
install.packages("ggplot2")
install.packages("knitr")
install.packages("plyr")
install.packages("dplyr")
install.packages("tidyverse")
install.packages("networkD3")
install.packages("visNetwork")
install.packages("BiocManager")
BiocManager::install("clusterProfiler", version = "3.8")
BiocManager::install("ReactomePA", version = "3.8")
BiocManager::install("org.Hs.eg.db", version = "3.8")
